### ISSUE TITLE
Exception caused by remove

### ISSUE THREAD

**Issue by bobbylaw** [AY2021S1-CS2103T-T12-1/tp#105]
When using remove without prefix, eg. remove 3, exception is thrown and not handled

Suggest to fix this on master branch first instead

![Capture](https://user-images.githubusercontent.com/64963147/95711201-ddc06a00-0c94-11eb-82a9-413f62248b04.PNG)
![Capture](https://user-images.githubusercontent.com/64963147/95711328-1e1fe800-0c95-11eb-8dec-69cc5ff34452.PNG)

**Comment by Wincenttjoi** [comment]
Errors not caught:
- [ ] remove 1
- [ ] remove 1 q/-123
- [ ] remove 1 q/
- [ ] remove 1 q/ASDF

Would be great if you can do unit testings for these too. Thank you! @wengfaing

**Comment by bobbylaw** [comment]
I can help @wengfaing with fixing the bugs, he can do the unit tests 👍
