### ISSUE TITLE
Invalid metric can pass through

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#110]
![image.png](https://images.zenhubusercontent.com/5f28227912b1f8051ba4372b/9e5433d5-9203-41f1-bd15-27c410ec9e6e)

Realized that invalid metric can still pass through. Shall we enforce metrics type by ENUM?

**Comment by Choo-Xing-Yu** [comment]
Disagree. Different restaurants may use different kinds of metrics and having metrics follow enums we may not cover all cases. In such cases edit command would suffice to correct the error

**Comment by saad-haider-pp** [comment]
> Disagree. Different restaurants may use different kinds of metrics and having metrics follow enums we may not cover all cases. In such cases edit command would suffice to correct the error

agreed

**Comment by Wincenttjoi** [comment]
@xnoobftw @halcon-blanco sure, if want to make it flexible its fine too. I'll close this thanks!
