### ISSUE TITLE
Change functionality of Find commands to use a weaker search

### ISSUE THREAD

**Issue by saad-haider-pp** [AY2021S1-CS2103T-T12-1/tp#116]
instead of matching words, should we just see if the search phrase is contained in any object.

**Comment by Choo-Xing-Yu** [comment]
You mean whether the search word is a substring of item?

**Comment by saad-haider-pp** [comment]
Yeah. It becomes a bigger issue when searching by phone number or address in the deliveries

**Comment by Choo-Xing-Yu** [comment]
could we implement that just for phone number and address?

**Comment by saad-haider-pp** [comment]
Yes that's possible. Is there anything else you think we should do as well. I'm thinking delivery order as well.

**Comment by Choo-Xing-Yu** [comment]
Delivery order sounds good! We could potentially reuse Quantity from Items package
