### ISSUE TITLE
Add Unit Tests for DeliveryFindCommand

### ISSUE THREAD

**Issue by saad-haider-pp** [AY2021S1-CS2103T-T12-1/tp#117]

**Comment by Choo-Xing-Yu** [comment]
@halcon-blanco isit okay if u took this? Since you implemented find for delivery!!

**Comment by saad-haider-pp** [comment]
@xnoobftw yea sure!

**Comment by saad-haider-pp** [comment]
Refer [8daa9e6](https://github.com/AY2021S1-CS2103T-T12-1/tp/commit/8daa9e64e4135bfea09d598a29ca6d47b3177b7f)
