### ISSUE TITLE
Delivery Model test cases

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#122]

**Comment by Wincenttjoi** [comment]
@AY2021S1-CS2103T-T12-1/developers do you guys prefer to standardize Order to not be able to accept empty string or just space? I can add the VALIDATION REGEX if you want, because the rest of the delivery objects seem to have this as a minimum req.

**Comment by bobbylaw** [comment]
sounds good 👍
