### ISSUE TITLE
Sequence diagram for "delete command" DG

### ISSUE THREAD

**Issue by Choo-Xing-Yu** [AY2021S1-CS2103T-T12-1/tp#149]

**Comment by Wincenttjoi** [comment]
@AY2021S1-CS2103T-T12-1/developers sorry that I couldn't attend the impromptu meeting. Just a short question, I'm curious why exactly sequence diagram for `delete` command but not others? Is there a specific reason?

**Comment by Choo-Xing-Yu** [comment]
Because there's alrdy one from AB3 and it's easier to refactor then to do from scratch

**Comment by Choo-Xing-Yu** [comment]
And I accidentally did it actually in my PR

**Comment by saad-haider-pp** [comment]
Can accidentally do my DG also

**Comment by Choo-Xing-Yu** [comment]
HAHAHAHAH @halcon-blanco
