### ISSUE TITLE
Enable Assertions (by Wed 23:59)

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#161]

**Comment by Choo-Xing-Yu** [comment]
It's enabled

**Comment by Choo-Xing-Yu** [comment]
refer https://github.com/AY2021S1-CS2103T-T12-1/tp/commit/977699417b62170546c6bb6c477710e13d9b377b

**Comment by Wincenttjoi** [comment]
@xnoobftw oh thanks. Its bcs I saw not green yet in the team project progress hahah, thanks!
