### ISSUE TITLE
User Guide Changes

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#197]
- [ ] Installation instructions (check if any update needed for oneshelf)
- [ ] make more distinguishable sections (white spaces)
- [ ] Line breaks
- [ ] fast-typist restaurant manager change awkward expression
- [ ] Reduce exclamation mark
- [x] Undo state max 20
- [x] Quick start features not clickable
- [ ] Quick start 3. Inventory Book to Oneshelf

**Comment by Wincenttjoi** [comment]
Step by step feature update:
XY - ADD
SAAD - EDIT, UNDO REDO
BOBBY - FIND, LIST
WF - REMOVE
W - HELP, DELETE

**Comment by Wincenttjoi** [comment]
@AY2021S1-CS2103T-T12-1/developers i'll be adding introduction as such
![image](https://user-images.githubusercontent.com/46394439/97140496-b6d75d00-1797-11eb-9d99-823c30417b99.png)
Fine with you guys?

**Comment by Wincenttjoi** [comment]
@AY2021S1-CS2103T-T12-1/developers 
She actually annotated this though, shall we change to tuna?
![image](https://user-images.githubusercontent.com/46394439/97140717-36fdc280-1798-11eb-8db8-c0db826d3fa2.png)

**Comment by Choo-Xing-Yu** [comment]
> @AY2021S1-CS2103T-T12-1/developers i'll be adding introduction as such
> ![image](https://user-images.githubusercontent.com/46394439/97140496-b6d75d00-1797-11eb-9d99-823c30417b99.png)
> Fine with you guys?

Looks good! 



> @AY2021S1-CS2103T-T12-1/developers
> She actually annotated this though, shall we change to tuna?
> ![image](https://user-images.githubusercontent.com/46394439/97140717-36fdc280-1798-11eb-8db8-c0db826d3fa2.png)

as discussed Tuna would be abetter choice as CHICKE outright looks like a typo
