### ISSUE TITLE
GUI is offset with latest GUIchange

### ISSUE THREAD

**Issue by Choo-Xing-Yu** [AY2021S1-CS2103T-T12-1/tp#47]
Issue:
![image](https://user-images.githubusercontent.com/61489581/93694079-24112600-fb3a-11ea-816c-09d587634d57.png)

![image](https://user-images.githubusercontent.com/61489581/93694069-093eb180-fb3a-11ea-8729-9445560506d4.png)

Tried changing DEFAULT_HEIGHT / DEFAULT_WIDTH in GuiSettings.java to no avail

**Comment by Choo-Xing-Yu** [comment]
Highly likely it's because of preference.json as AB3 tries to read userpref before inputting default values for GUI

**Comment by Wincenttjoi** [comment]
Thanks for info, will trace and refactor this to make it work and PR again
