### ISSUE TITLE
GUI layout to split into 2 sections

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#95]
- [x] Expand command box at the bottom

**Comment by saad-haider-pp** [comment]
@AY2021S1-CS2103T-T12-1/developers do you want the Delivery section and Items section to be of equal width, or the current width they have right now

**Comment by saad-haider-pp** [comment]
Currently it looks like this
![image](https://user-images.githubusercontent.com/50513077/95714746-414d9600-0c9b-11eb-883e-50e16bcd81ee.png)

**Comment by Choo-Xing-Yu** [comment]
IMO having more space for delivery makes sense as it composes more information

**Comment by Wincenttjoi** [comment]
@halcon-blanco i'm fine with this, since we might need to change again in the future into 3 sections so no issue. For the colouring, is it easy to implement colouring to be conditional (red vs green if stock falls below 20%)? If its a huge task we can create a separate task.

Further improvement:
Low priority: I didn't do the GUI for help toolbar on top to open up the 2 different help windows since the app is meant for CLI primarily. But feel free to connect them if you want :)

**Comment by saad-haider-pp** [comment]
>  For the colouring, is it easy to implement colouring to be conditional (red vs green if stock falls below 20%)? If its a huge task we can create a separate task.

Yes that is very doable

> Further improvement:
> Low priority: I didn't do the GUI for help toolbar on top to open up the 2 different help windows since the app is meant for CLI primarily. But feel free to connect them if you want :)

I'll check it out
